name: Release

on:
  release:
    types:
      - published # reacts to releases and pre-releases, but not their drafts

jobs:

  release:

    name: Release

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 8
        uses: actions/setup-java@v4.7.0
        with:
          distribution: "temurin"
          java-version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: lts/hydrogen

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest

      - name: Build the jar and update pom.xml's version
        run: clojure -X:jar

      - name: Deploy the jar and pom files to Clojars
        run: clojure -X:deploy
        env:
          CLOJARS_USERNAME: green-coder
          CLOJARS_PASSWORD: "${{ secrets.CLOJARS_DEPLOY_TOKEN }}"
